sudo: required
services:
  - docker

before_install:
  - docker build -t dandrewsify/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dandrewsify/react-test npm test -- --coverage

after_success:
  - docker build -t dandrewsify/multi-client ./client
  - docker build -t dandrewsify/multi-nginx ./nginx
  - docker build -t dandrewsify/multi-server ./server
  - docker build -t dandrewsify/multi-worker ./worker
  # LOG IN  TO DOCKER CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dandrewsify/multi-client
  - docker push dandrewsify/multi-nginx
  - docker push dandrewsify/multi-server
  - docker push dandrewsify/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: us-east-1
#   app: MultiDocker
#   env: multidockerenv
#   bucket_name: elasticbeanstalk-us-east-1-561382394780
#   bucket-path: docker-multi
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY